[package]
name = "system76-firmware"
version = "1.0.2"
authors = ["Jeremy Soller <jeremy@system76.com>"]

[[bin]]
name = "system76-firmware-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "system76-firmware-daemon"
path = "src/bin/daemon.rs"

[dependencies]
buildchain = "0.4.8"
dbus = "0.6.4"
ecflash = { git = "https://github.com/system76/ecflash.git", branch = "stable" }
libc = "0.2.50"
plain = "0.2.3"
rust-lzma = "0.4.0"
serde_json = "1.0.39"
sha2 = "0.8.0"
tar = "0.4.21"
tempdir = "0.3.7"
uuid = "0.7.2"

[profile.release]
lto = true
