[package]
name = "system76-firmware"
version = "1.0.2"
authors = ["Jeremy Soller <jeremy@system76.com>"]

[[bin]]
name = "system76-firmware-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "system76-firmware-daemon"
path = "src/bin/daemon.rs"

[dependencies]
buildchain = { git = "https://github.com/szydell/buildchain" }
dbus = "0.6"
ecflash = { git = "https://github.com/system76/ecflash.git", branch = "stable" }
libc = "0.2"
plain = "0.2"
rust-lzma = "0.2"
serde_json = "1.0"
sha2 = "0.7.0"
tar = "0.4"
tempdir = "0.3"
uuid = "0.6"

[profile.release]
lto = true
